
export enum BuildStateEnum {
    BEFORE_TRIGGER = 'BEFORE_TRIGGER',
    BUILDING = 'BUILDING',
    BUILT = 'BUILT',
    CANCEL_REQUESTED = 'CANCEL_REQUESTED',
    CANCELLED = 'CANCELLED',
    FAILED_INPUT_PREPARE_REPORT_VALIDATION = 'FAILED_INPUT_PREPARE_REPORT_VALIDATION',
    FAILED_PRE_CONDITIONS = 'FAILED_PRE_CONDITIONS',
    FAILED = 'FAILED',
    UNKNOWN = 'UNKNOWN',
    RVF_QUEUED = 'RVF_QUEUED',
    RVF_RUNNING = 'RVF_RUNNING',
    RELEASE_COMPLETE = 'RELEASE_COMPLETE',
    RELEASE_COMPLETE_WITH_WARNINGS = 'RELEASE_COMPLETE_WITH_WARNINGS'
}
